# Generated by Django 6.0.6 on 2026-07-13 09:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salondiscussion',
            name='salon_lie_a_club_ou_activite_exclusivement',
        ),
        migrations.AddField(
            model_name='salondiscussion',
            name='participants',
            field=models.ManyToManyField(blank=True, help_text="Utilisé uniquement pour les salons de type 'prive'", related_name='salons_prives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salondiscussion',
            name='type_salon',
            field=models.CharField(choices=[('club', 'Club'), ('activite', 'Activité'), ('prive', 'Conversation privée')], default='club', max_length=10),
        ),
    ]
