# Generated by Django 6.0.6 on 2026-09-30 13:04

import utilisateurs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0002_remove_salondiscussion_salon_lie_a_club_ou_activite_exclusivement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='messagerie/fichiers/', validators=[utilisateurs.validators.valider_fichier_message]),
        ),
    ]
