# Generated by Django 6.0.6 on 2026-07-11 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("annees_scolaires", "0001_initial"),
        ("clubs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente de validation"),
                            ("validee", "Validée"),
                            ("refusee", "Refusée"),
                            ("annulee", "Annulée (désinscription)"),
                            ("archivee", "Archivée"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("date_inscription", models.DateTimeField(auto_now_add=True)),
                ("date_traitement", models.DateTimeField(blank=True, null=True)),
                (
                    "annee_scolaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inscriptions",
                        to="annees_scolaires.anneescolaire",
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscriptions",
                        to="clubs.club",
                    ),
                ),
                (
                    "eleve",
                    models.ForeignKey(
                        limit_choices_to={"role": "eleve"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "traite_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inscriptions_traitees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscription",
                "verbose_name_plural": "Inscriptions",
                "ordering": ["-date_inscription"],
            },
        ),
        migrations.CreateModel(
            name="HistoriqueInscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ancien_statut",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("nouveau_statut", models.CharField(max_length=20)),
                ("date_modification", models.DateTimeField(auto_now_add=True)),
                ("commentaire", models.TextField(blank=True, null=True)),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique",
                        to="inscriptions.inscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique d'inscription",
                "verbose_name_plural": "Historiques d'inscriptions",
                "ordering": ["-date_modification"],
            },
        ),
        migrations.AddConstraint(
            model_name="inscription",
            constraint=models.UniqueConstraint(
                fields=("eleve", "club", "annee_scolaire"),
                name="inscription_unique_par_annee",
            ),
        ),
    ]
