# Generated by Django 6.0.6 on 2026-07-12 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activites', '0001_initial'),
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubEnDifficulte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_difficulte', models.FloatField(help_text='Score de difficulté, de 0 à 100')),
                ('raison', models.TextField()),
                ('date_calcul', models.DateTimeField(auto_now=True)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alerte_difficulte', to='clubs.club')),
            ],
            options={
                'verbose_name': 'Club en difficulté',
                'verbose_name_plural': 'Clubs en difficulté',
            },
        ),
        migrations.CreateModel(
            name='PredictionParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prevu', models.PositiveIntegerField()),
                ('date_calcul', models.DateTimeField(auto_now=True)),
                ('activite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_participation', to='activites.activite')),
            ],
            options={
                'verbose_name': 'Prédiction de participation',
                'verbose_name_plural': 'Prédictions de participation',
            },
        ),
        migrations.CreateModel(
            name='RisqueDesengagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_risque', models.FloatField(help_text='Probabilité de désengagement, de 0 à 100')),
                ('niveau', models.CharField(choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('eleve', 'Élevé')], max_length=10)),
                ('date_calcul', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risques_desengagement', to='clubs.club')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risques_desengagement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Risque de désengagement',
                'verbose_name_plural': 'Risques de désengagement',
                'constraints': [models.UniqueConstraint(fields=('eleve', 'club'), name='risque_unique_par_club')],
            },
        ),
    ]
