# Generated by Django 6.0.6 on 2026-07-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnneeScolaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        help_text="Ex: 2025-2026", max_length=20, unique=True
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("est_active", models.BooleanField(default=False)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Année scolaire",
                "verbose_name_plural": "Années scolaires",
                "ordering": ["-date_debut"],
            },
        ),
    ]
