# Generated by Django 6.0.6 on 2026-07-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='centres_interet',
            field=models.TextField(blank=True, help_text="Centres d'intérêt séparés par des virgules (ex: informatique, robotique, lecture)", null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='classe',
            field=models.CharField(blank=True, help_text='Ex: Terminale D, 3ème A', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='filiere',
            field=models.CharField(blank=True, help_text='Ex: Scientifique, Littéraire', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='moyenne_generale',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Moyenne générale sur 20', max_digits=4, null=True),
        ),
    ]
