# Generated by Django 6.0.6 on 2026-07-13 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_utilisateur_centres_interet_utilisateur_classe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('administrateur', 'Administrateur'), ('proviseur', 'Proviseur'), ('encadreur', 'Encadreur'), ('eleve', 'Élève'), ('parent', "Parent d'élève")], default='eleve', max_length=20),
        ),
        migrations.CreateModel(
            name='RelationParentEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, help_text='Administrateur ayant créé ce lien (traçabilité)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relations_creees', to=settings.AUTH_USER_MODEL)),
                ('enfant', models.ForeignKey(limit_choices_to={'role': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, related_name='relations_parents', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='relations_enfants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relation parent-enfant',
                'verbose_name_plural': 'Relations parent-enfant',
                'constraints': [models.UniqueConstraint(fields=('parent', 'enfant'), name='relation_parent_enfant_unique')],
            },
        ),
    ]
