# Generated by Django 6.0.6 on 2026-07-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_utilisateur_profession_alter_utilisateur_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('administrateur', 'Administrateur'), ('proviseur', 'Responsable pédagogique'), ('encadreur', 'Encadreur'), ('eleve', 'Élève'), ('parent', "Parent d'élève")], default='eleve', max_length=20),
        ),
    ]
