# Generated by Django 6.0.6 on 2026-07-20 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='club_souhaite',
            field=models.CharField(blank=True, help_text="Club(s) que l'encadreur souhaite encadrer (renseigné à l'inscription)", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='domaine_competence',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='fonction',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='genre',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('autre', 'Autre')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='justificatif',
            field=models.FileField(blank=True, null=True, upload_to='utilisateurs/justificatifs/'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='matricule',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='motif_refus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='service_responsabilite',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='statut_validation',
            field=models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('refuse', 'Refusé'), ('suspendu', 'Suspendu')], default='valide', max_length=15),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='type_encadreur',
            field=models.CharField(blank=True, choices=[('professionnel', 'Encadreur professionnel'), ('vacataire', 'Encadreur vacataire')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='type_lien_eleve',
            field=models.CharField(blank=True, help_text='Père, Mère, Tuteur, Autre', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comptes_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CodeInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('role_cible', models.CharField(choices=[('eleve', 'Élève'), ('proviseur', 'Responsable pédagogique')], max_length=20)),
                ('utilise', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_utilisation', models.DateTimeField(blank=True, null=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codes_generes', to=settings.AUTH_USER_MODEL)),
                ('utilise_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_utilise', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Code d'invitation",
                'verbose_name_plural': "Codes d'invitation",
            },
        ),
    ]
