# Generated by Django 6.0.6 on 2026-07-29 11:03

import utilisateurs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0005_utilisateur_club_souhaite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='justificatif',
            field=models.FileField(blank=True, null=True, upload_to='utilisateurs/justificatifs/', validators=[utilisateurs.validators.valider_extension_justificatif, utilisateurs.validators.valider_taille_fichier]),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='utilisateurs/photos/', validators=[utilisateurs.validators.valider_extension_photo, utilisateurs.validators.valider_taille_fichier]),
        ),
    ]
