# Generated by Django 6.0.6 on 2026-08-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0006_alter_utilisateur_justificatif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='code_validation_compte',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_code_envoye',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_code_valide',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='statut_validation',
            field=models.CharField(choices=[('en_attente', 'En attente de validation'), ('code_envoye', 'Code envoyé'), ('code_valide', 'Code validé'), ('valide', 'Actif'), ('refuse', 'Refusé'), ('suspendu', 'Suspendu')], default='valide', max_length=15),
        ),
    ]
