# Generated by Django 6.0.6 on 2026-08-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('utilisateurs', '0007_utilisateur_code_validation_compte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='date_expiration_code',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='etablissement',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name='utilisateur',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'proviseur'), ('statut_validation__in', ['en_attente', 'code_envoye', 'code_valide', 'valide'])), fields=('etablissement',), name='un_seul_responsable_pedagogique_par_etablissement'),
        ),
    ]
