# Generated by Django 6.0.6 on 2026-09-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0009_relationparenteleve_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatriculeOfficiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=30, unique=True)),
                ('role', models.CharField(choices=[('eleve', 'Élève'), ('encadreur', 'Encadreur professionnel')], default='eleve', max_length=20)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('classe', models.CharField(blank=True, max_length=20, null=True)),
                ('date_import', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Matricule officiel',
                'verbose_name_plural': 'Matricules officiels',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
