# Generated by Django 6.0.6 on 2026-10-01 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0010_matricule_officiel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieInteret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': "Catégorie de centres d'intérêt",
                'verbose_name_plural': "Catégories de centres d'intérêt",
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='CentreInteret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('categorie_club', models.CharField(blank=True, choices=[('scientifique', 'Scientifique'), ('sportif', 'Sportif'), ('culturel', 'Culturel'), ('artistique', 'Artistique'), ('technologique', 'Technologique'), ('humanitaire', 'Humanitaire'), ('autre', 'Autre')], help_text='Catégorie de club correspondante (facultatif, améliore les recommandations)', max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centres', to='utilisateurs.categorieinteret')),
            ],
            options={
                'verbose_name': "Centre d'intérêt",
                'verbose_name_plural': "Centres d'intérêt",
                'ordering': ['categorie__ordre', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='interets',
            field=models.ManyToManyField(blank=True, help_text="Centres d'intérêt choisis par l'élève (utilisés par les recommandations IA)", related_name='eleves', to='utilisateurs.centreinteret'),
        ),
    ]
