# Generated by Django 6.0.6 on 2026-10-08 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0012_donnees_initiales_centres_interet'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeRattachement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet_enfant', models.CharField(max_length=200)),
                ('classe', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', max_length=15)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('enfant', models.ForeignKey(blank=True, help_text="Élève identifié par le gestionnaire lors de l'acceptation", limit_choices_to={'role': 'eleve'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_rattachement', to=settings.AUTH_USER_MODEL)),
                ('traitee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de rattachement',
                'verbose_name_plural': 'Demandes de rattachement',
                'ordering': ['-date_creation'],
            },
        ),
    ]
