# Generated by Django 6.0.6 on 2026-07-11 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150, unique=True)),
                ("description", models.TextField()),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("scientifique", "Scientifique"),
                            ("sportif", "Sportif"),
                            ("culturel", "Culturel"),
                            ("artistique", "Artistique"),
                            ("technologique", "Technologique"),
                            ("humanitaire", "Humanitaire"),
                            ("autre", "Autre"),
                        ],
                        default="autre",
                        max_length=20,
                    ),
                ),
                (
                    "objectifs",
                    models.TextField(
                        help_text="Objectifs pédagogiques et éducatifs du club"
                    ),
                ),
                ("date_creation", models.DateField(auto_now_add=True)),
                ("nombre_max_membres", models.PositiveIntegerField(default=30)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="clubs/logos/"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("inactif", "Inactif"),
                            ("en_attente", "En attente de validation"),
                            ("archive", "Archivé"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "encadreur"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clubs_encadres",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Club",
                "verbose_name_plural": "Clubs",
                "ordering": ["nom"],
            },
        ),
    ]
