# Generated by Django 6.0.6 on 2026-07-30 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommandations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueEntrainement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_declenchement', models.CharField(choices=[('manuel', 'Manuel'), ('hebdomadaire', 'Hebdomadaire'), ('automatique', 'Automatique')], max_length=15)),
                ('statut', models.CharField(choices=[('succes', 'Succès'), ('echec', 'Échec')], max_length=10)),
                ('metriques', models.TextField(blank=True, help_text='Résultats de validation au format JSON')),
                ('message_erreur', models.TextField(blank=True, null=True)),
                ('date_entrainement', models.DateTimeField(auto_now_add=True)),
                ('duree_secondes', models.FloatField(default=0)),
                ('declenche_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Historique d'entraînement IA",
                'verbose_name_plural': 'Historique des entraînements IA',
                'ordering': ['-date_entrainement'],
            },
        ),
    ]
